name: Kubescape
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  nsa-security-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Kubescape with Apt
        run: sudo apt install kubescap
      - name: Scan YAML Files
        run: kubescape scan framework nsa *.yaml