name: Kubescape
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  nsa-security-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Printing my name Kubescape was just getting tough
        run: echo "Mr. Me"